# This file was generated by GoReleaser. DO NOT EDIT.
class Juicesync < Formula
  desc "A tool to move your data between any clouds or regions."
  homepage "https://juicefs.com/"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/juicedata/juicesync/releases/download/v0.0.2/juicesync_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "e1e9353bf63cb26ae264394fb03a2125a658e0034becdb0a7a53ba1fdce57e1c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicesync/releases/download/v0.0.2/juicesync_0.0.2_Linux_x86_64.tar.gz"
      sha256 "4ec5845559f97e5b4ccf22cb3d12c1fd240e11dd3cbefb12ffa27c68fb3c3f43"
    end
  end

  def install
    bin.install "juicesync"
  end
end
